[workspace]
members = [
    "project_1", 
    "project_2",
    "project_3",
    "project_4",
    "project_5",
    "raft",
    "crates/labrpc",
    "crates/labcodec",
    "crates/linearizability"
, "fly_io_challenge/dist_echo"]
