[package]
name = "project_1"
version = "0.1.0"
edition = "2021"
authors= ["Philip Daquin"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "4.0.32"

[dev-dependencies]
assert_cmd = "2.0.8"
predicates = "2.1.5"
